<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <xacro:include filename="inertial_macros.xacro"/>

    <xacro:property name="chassis_base_length" value="0.3556"/>
    <xacro:property name="chassis_base_width" value="0.2032"/>
    <xacro:property name="chassis_base_height" value="0.1397"/>
    <xacro:property name="chassis_base_mass" value="1.0"/>
    <xacro:property name="chassis_top_length" value="0.4064"/>
    <xacro:property name="chassis_top_width" value="0.254"/>
    <xacro:property name="chassis_top_height" value="0.1905"/>
    <xacro:property name="chassis_top_mass" value="1.0"/>
    <xacro:property name="lid_thickness" value="0.0254"/>
    <xacro:property name="wheel_radius" value="0.0635"/>
    <xacro:property name="wheel_thickness" value="0.0254"/>
    <xacro:property name="wheel_mass" value="0.05"/>
    <xacro:property name="wheel_offset_y" value="0.1143"/>
    <xacro:property name="wheel_offset_z" value="0.026035"/>

    <material name="white">
        <color rgba="1 1 1 1" />
    </material>

    <material name="orange">
        <color rgba="1 0.3 0.1 1"/>
    </material>

    <material name="blue">
        <color rgba="0.2 0.2 1 1"/>
    </material>

    <material name="black">
        <color rgba="0.25 0.25 0.25 1"/>
    </material>

    <material name="red">
        <color rgba="1 0 0 1"/>
    </material>

    <material name="gray">
        <color rgba="0.8 0.8 0.8 1"/>
    </material>

    <material name="gold">
        <color rgba="1 0.84 0 1"/>
    </material>

    <!-- BASE LINK -->

    <link name="base_link">

    </link>

    <!-- BASE_FOOTPRINT LINK -->

    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <link name="base_footprint">
    </link>


    <!-- CHASSIS BASE LINK -->

    <joint name="chassis_base_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis_base"/>
        <origin xyz="${-chassis_base_length/2} 0 ${-wheel_offset_z}"/>
    </joint>

    <link name="chassis_base">
        <visual>
            <origin xyz="${chassis_base_length/2} 0 ${chassis_base_height/2}"/>
            <geometry>
                <box size="${chassis_base_length} ${chassis_base_width} ${chassis_base_height}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <origin xyz="${chassis_base_length/2} 0 ${chassis_base_height/2}"/>
            <geometry>
                <box size="${chassis_base_length} ${chassis_base_width} ${chassis_base_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.5" x="${chassis_base_length}" y="${chassis_base_width}" z="${chassis_base_height}">
            <!-- origin should match visual origin -->
            <origin xyz="${chassis_base_length/2} 0 ${chassis_base_height/2}" rpy="0 0 0"/> 
        </xacro:inertial_box>
    </link>

    <gazebo reference="chassis_base">
        <material>Gazebo/Black</material>
    </gazebo>

    <!-- CHASSIS TOP LINK -->

    <joint name="chassis_top_joint" type="fixed">
        <origin xyz="${chassis_base_length/2} 0 ${chassis_base_height}" rpy="0 0 0" />
        <parent link="chassis_base"/>
        <child link="chassis_top"/>
    </joint>

    <link name="chassis_top">
        <visual>
            <origin xyz="0 0 ${chassis_top_height/2}"/>
            <geometry>
                <box size="${chassis_top_length} ${chassis_top_width} ${chassis_top_height}" />
            </geometry>
            <material name="gold" />
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="${chassis_top_length} ${chassis_top_width} ${chassis_top_height}" />
            </geometry>
        </collision>
    </link>

    <gazebo reference="chassis_top">
        <material>Gazebo/Gold</material>
    </gazebo>

    <!-- LID LINK -->

    <joint name="lid_joint" type="fixed">
        <origin xyz="0 0 ${chassis_top_height}" />
        <parent link="chassis_top"/>
        <child link="lid"/>
    </joint>

    <link name="lid">
        <visual>
            <origin xyz="0 0 ${lid_thickness/2}" />
            <geometry>
                <box size="${chassis_top_length} ${chassis_top_width} ${lid_thickness}" />
            </geometry>
            <material name="black" />
        </visual>
        <collision>
            <origin xyz="0 0 ${lid_thickness}" />
            <geometry>
                <box size="${chassis_top_length} ${chassis_top_width} ${lid_thickness}" />
            </geometry>
        </collision>
    </link>

    <gazebo reference="lid">
        <material>Gazebo/Black</material>
    </gazebo>

    <!-- LEFT WHEEL LINK -->

    <joint name="left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel"/>
        <origin xyz="0 ${wheel_offset_y} 0" rpy="-${pi/2} 0 0" />
        <axis xyz="0 0 1"/>
    </joint>

    <link name="left_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="gray"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <!-- origin should match visual origin -->
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="left_wheel">
        <material>Gazebo/Gray</material>
    </gazebo>

    <!-- RIGHT WHEEL LINK -->

    <joint name="right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel"/>
        <origin xyz="0 ${-wheel_offset_y} 0" rpy="${pi/2} 0 0" />
        <axis xyz="0 0 -1"/>
    </joint>

    <link name="right_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>-
            <material name="gray"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <!-- origin should match visual origin -->
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="right_wheel">
        <material>Gazebo/Gray</material>
    </gazebo>
 
</robot>